In [1]:
from bs4 import BeautifulSoup
import requests

In [2]:
url = "https://www.scrapethissite.com/pages/forms/"

In [3]:
page = requests.get(url)

In [4]:
soup = BeautifulSoup(page.text,'html')

In [ ]:
print(soup)

In [ ]:
print(soup.prettify())

In [16]:
soup.find_all('p', class_='lead')

[<p class="lead">
                             Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.
                             Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.
                         </p>]

In [5]:
title = soup.find_all('th')
title_header = [titleh.text.strip() for titleh in title]
print(title_header)

['Team Name', 'Year', 'Wins', 'Losses', 'OT Losses', 'Win %', 'Goals For (GF)', 'Goals Against (GA)', '+ / -']

In [18]:
soup.find('p', class_='lead').text.strip()

'Browse through a database of NHL team stats since 1990. Practice building a scraper that handles common website interface components.\n                            Take a look at how pagination and search elements change the URL as your browse. Build a web scraper that can conduct searches and paginate through the results.'

In [6]:
import pandas as pd
df = pd.DataFrame(columns=title_header)

In [7]:
df

Empty DataFrame
Columns: [Team Name, Year, Wins, Losses, OT Losses, Win %, Goals For (GF), Goals Against (GA), + / -]
Index: []

In [8]:
data = soup.find_all('tr')

In [9]:
for row in data[1:]:
    row_data = row.find_all('td')
    ind_row_data = [data.text.strip() for data in row_data ]
    
    length=len(df)
    df.loc[length] = ind_row_data

In [10]:
df

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21